schema_version = "1.0.0"

# Runchat Blender Addon manifest
id = "runchat_blender_addon"
version = "1.2.0"
name = "Runchat Blender Addon"
tagline = "Integrates Runchat workflows directly into Blender"
maintainer = "Runchat"
type = "add-on"

# Documentation and support
website = "https://docs.runchat.app"

# Optional: tag list for categorization
tags = ["System", "Pipeline", "Import-Export"]

blender_version_min = "4.2.0"

# License - using GPL-3.0 as it's compatible with Blender
license = [
  "SPDX:GPL-3.0-or-later",
]




# Bundle 3rd party Python modules as wheels
wheels = [
  "./wheels/certifi-2025.7.9-py3-none-any.whl",
  "./wheels/charset_normalizer-3.4.2-cp311-cp311-macosx_10_9_universal2.whl",
  "./wheels/idna-3.10-py3-none-any.whl",
  "./wheels/pillow-11.3.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/requests-2.32.4-py3-none-any.whl",
  "./wheels/urllib3-2.5.0-py3-none-any.whl",
]

# Permissions - this addon needs network access to communicate with Runchat
[permissions]
network = "Connect to Runchat API to sync workflows and data"
files = "Import/export workflow files and assets"

# Build settings to exclude development files
[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "*.pyc",
  "test_*",
  "BUILD_GUIDE.md",
] 